version: '3'

services: 
  db: 
    container_name: 'db'
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes: 
      - pg_data:/data/postgres
    networks:
      - internal  

  backend: 
    container_name: 'backend'
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-image
    env_file: .env
    restart: always
    ports: 
     - '4000:3000'
    depends_on: 
      - db
    networks:
      - internal

  frontend:
    container_name: 'frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-image
    ports:
      - '8081:80'
    restart: always
    networks:
      - external

volumes:
  pg_data:

networks: 
  internal:
  external: